app:
  jwt:
    secret: ${JWT_SECRET:replace_me}
    expiration_ms: ${JWT_EXPIRATION_MS:3600000}
    refresh_expiration_ms: ${JWT_REFRESH_EXPIRATION_MS:86400000}
  admin:
    email: ${DEFAULT_ADMIN_EMAIL:}
    password: ${DEFAULT_ADMIN_PASSWORD:}
